//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zh_g3w0i5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVD_RentalEntities : DbContext
    {
        public DVD_RentalEntities()
            : base("name=DVD_RentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DVD> DVDs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
    }
}
